version: "3.7"

services:
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --requirepass redis-password
    expose:
      - 6379

  game-logic:
    container_name: game-logic-service
    environment:
      - REDIS_HOST_NAME=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis-password
      - JWT_KEY=0u8feufbeufbefdwgbytactrvanipol]
      - AI_SERVICE_URL=http://minimal-python:8888
      - USER_SERVICE_URL=http://user_data_service:80
      - CHAT_SERVICE_URL=http://chatservice:8124
    build:
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8080:8080"
