server:
  port: 8080
external:
  service:
    user-service:
      url: "https://api.publicapis.org"

spring:
  data:
    redis:
      port: 6379
      host: redis

jwt:
  key: 0u8feufbeufbefdwgbytactrvanipol]